name: IncreaseSpeedPlugin
version: '1.2-SNAPSHOT'
main: org.plugins.minevidencia.IncreaseSpeedPlugin
api-version: '1.21'


commands:
  speed:
    description: Aplica efeito de velocidade ao jogador
    usage: /<speed> [0 - 4]